#!/bin/bash
cd /mnt/hgfs/sharedFolder/
gcc -o test indiana.c
#gcc -c pattach.c
yes | cp /mnt/hgfs/sharedFolder/pattach.c /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/pattach.o /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/entry.S /usr/src/linux-2.4.18-14custom/arch/i386/kernel/