#!/bin/bash
#cd /mnt/hgfs/sharedFolder/
#gcc -std=c99 teston.c -o test
#gcc -std=c99 teston2.c -o 2test
#yes | cp /mnt/hgfs/sharedFolder/hw2_syscalls.c /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/sched.c /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/fork.c /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/Makefile /usr/src/linux-2.4.18-14custom/kernel/
#yes | cp /mnt/hgfs/sharedFolder/sched.h /usr/src/linux-2.4.18-14custom/include/linux/
#yes | cp /mnt/hgfs/sharedFolder/entry.S /usr/src/linux-2.4.18-14custom/arch/i386/kernel/

#yes | cp /usr/src/linux-2.4.18-14custom/kernel/Makefile /mnt/hgfs/sharedFolder/ 
#cd /usr/src/linux-2.4.18-14custom
#tar -czf kernel.tar.gz kernel/hw2_syscalls.c kernel/sched.c kernel/fork.c kernel/Makefile include/linux/sched.h arch/i386/kernel/entry.S
